# Generated by Django 5.0.6 on 2024-10-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
