# Generated by Django 5.0.6 on 2024-10-18 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_likes',
            field=models.ManyToManyField(related_name='User_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(related_name='User_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
