# Generated by Django 5.0.6 on 2024-10-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_comment_user_likes_post_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
