# Generated by Django 5.0.6 on 2025-01-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_interest_user_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='post_tag', to='network.interest'),
        ),
    ]
